# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_email", "0001_initial"),
        ("django_email", "0002_allegrovirtualproduct_additional_key_name_and_more"),
        ("django_email", "0003_returnsreturnconfirmation_loyaltycouponconfirmation_and_more"),
        ("django_email", "0004_channel_from_email"),
        ("django_email", "0005_accountsnewaccount_announce"),
        ("django_email", "0006_channel_from_name"),
        ("django_email", "0007_channel_logo_max_width"),
        ("django_email", "0008_channel_from_t9n"),
        ("django_email", "0009_remove_channel_footer_copy_t9n_and_more"),
        ("django_email", "0010_agreementsnewslettersignup"),
        ("django_email", "0011_contactformsbookingadminnotification_and_more"),
        ("django_email", "0012_contactformsbookingadminnotification_header_title_and_more"),
        ("django_email", "0013_alter_contactformsbookingadminnotification_label_company_and_more"),
        ("django_email", "0014_checkoutinvoice"),
        ("django_email", "0014_contactformsclientcopy"),
        ("django_email", "0015_channel_bcc_email_channel_bcc_email_types"),
        ("django_email", "0015_checkoutvoucher"),
        ("django_email", "0015_merge_checkoutinvoice_contactformsclientcopy"),
        ("django_email", "0016_merge_checkoutvoucher_clientcopy"),
    ]

    # Data op from the old 0009 (Channel -> LangChannelConfig backfill) is omitted:
    # on a fresh database there are no Channel rows, so it was a guaranteed no-op.

    dependencies = [
        ("django_regional", "0002_reset_pk_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=64)),
                ("from_name", models.CharField(blank=True, max_length=256, null=True)),
                ("from_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "from_t9n",
                    models.JSONField(
                        blank=True,
                        help_text="Should be in format: {pl: {from_name: ABC, from_email: abc@example.com}}",
                        null=True,
                    ),
                ),
                ("main_background_color", models.CharField(default="#FFFFFF", max_length=10)),
                ("body_background_color", models.CharField(default="#EDEDED", max_length=10)),
                ("main_text_color", models.CharField(default="#141414", max_length=10)),
                ("brand_text_color", models.CharField(default="#404040", max_length=10)),
                ("font_family", models.CharField(default="'Inter', sans-serif", max_length=256)),
                ("logo_max_width", models.CharField(default="100", max_length=20)),
                (
                    "bcc_email",
                    models.EmailField(
                        blank=True,
                        help_text="Administrator address that receives a blind carbon copy (BCC) of selected emails. The original recipient does not see that a copy was sent.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "bcc_email_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email types for which a BCC copy is sent to the BCC address.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllegroVirtualProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="If you want order number in subject, please fill this field with |order_id|",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add order number, please fill this field with |order_id|",
                        null=True,
                    ),
                ),
                ("products", models.TextField(blank=True, null=True)),
                ("key_name", models.CharField(blank=True, max_length=256, null=True)),
                ("additional_key_name", models.CharField(blank=True, max_length=256, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
            ],
            options={
                "verbose_name": "[Allegro] Virtual Product",
                "verbose_name_plural": "[Allegro] Virtual Products",
            },
        ),
        migrations.CreateModel(
            name="AgreementsNewsletterSignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                ("confirm_copy", models.TextField(blank=True, null=True)),
                ("confirm_button", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
            ],
            options={
                "verbose_name": "[Agreements] Newsletter Signup",
                "verbose_name_plural": "[Agreements] Newsletter Signups",
            },
        ),
        migrations.CreateModel(
            name="AccountsResetPassword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                ("welcome", models.TextField(blank=True, null=True)),
                ("reset_button", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
            ],
            options={
                "verbose_name": "[Accounts] Reset Password",
                "verbose_name_plural": "[Accounts] Reset Passwords",
            },
        ),
        migrations.CreateModel(
            name="AccountsNewAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                ("announce", models.TextField(blank=True, null=True)),
                ("confirm_button", models.TextField(blank=True, null=True)),
                ("thank_you", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
            ],
            options={
                "verbose_name": "[Accounts] New Account",
                "verbose_name_plural": "[Accounts] New Accounts",
            },
        ),
        migrations.CreateModel(
            name="CheckoutInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject. Use |order_id| as placeholder.", max_length=256, null=True
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Intro text. Use |user_name| and |order_id| as placeholders.", null=True
                    ),
                ),
                ("body", models.TextField(blank=True, help_text="Main body text.", null=True)),
                ("footer", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages enabled in EMAIL_AVAILABLE_LANGUAGES setting work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Checkout] Invoice",
                "verbose_name_plural": "[Checkout] Invoices",
            },
        ),
        migrations.CreateModel(
            name="CheckoutVirtualProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="If you want order number in subject, please fill this field with |order_id|",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add order number, please fill this field with |order_id|",
                        null=True,
                    ),
                ),
                ("products", models.TextField(blank=True, null=True)),
                ("key_name", models.CharField(blank=True, max_length=256, null=True)),
                ("additional_key_name", models.CharField(blank=True, max_length=256, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Checkout] Virtual Product",
                "verbose_name_plural": "[Checkout] Virtual Products",
            },
        ),
        migrations.CreateModel(
            name="CheckoutVoucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issued_on_purchase_subject", models.CharField(blank=True, max_length=256, null=True)),
                ("issued_by_admin_subject", models.CharField(blank=True, max_length=256, null=True)),
                ("resend_subject", models.CharField(blank=True, max_length=256, null=True)),
                ("welcome", models.TextField(blank=True, null=True)),
                ("code_label", models.CharField(blank=True, max_length=128, null=True)),
                ("pin_label", models.CharField(blank=True, max_length=128, null=True)),
                ("expires_label", models.CharField(blank=True, max_length=128, null=True)),
                ("balance_label", models.CharField(blank=True, max_length=128, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages enabled in EMAIL_AVAILABLE_LANGUAGES are honored.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Checkout] Voucher Email",
                "verbose_name_plural": "[Checkout] Voucher Emails",
            },
        ),
        migrations.CreateModel(
            name="ContactFormsBookingAdminNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                (
                    "header_title",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="H2 heading at the top of the email. Overrides 'New booking' default.",
                    ),
                ),
                (
                    "intro_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered above the booking facts."),
                ),
                (
                    "label_datetime",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the date & time row.", max_length=256
                    ),
                ),
                (
                    "label_name",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the booker name row.", max_length=256
                    ),
                ),
                (
                    "label_email",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the email row.", max_length=256
                    ),
                ),
                (
                    "label_phone",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the phone row.", max_length=256
                    ),
                ),
                (
                    "label_company",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the company row.", max_length=256
                    ),
                ),
                (
                    "label_message",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the message row.", max_length=256
                    ),
                ),
                (
                    "label_video",
                    models.CharField(
                        blank=True, default="", help_text="Inline label before the video meeting link.", max_length=256
                    ),
                ),
                (
                    "closing_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered after the meet link."),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Contact Forms] Booking Admin Notification",
                "verbose_name_plural": "[Contact Forms] Booking Admin Notifications",
            },
        ),
        migrations.CreateModel(
            name="ContactFormsBookingConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                (
                    "header_title",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="H2 heading at the top of the email. Overrides 'Your booking is confirmed' default.",
                    ),
                ),
                (
                    "greeting_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Greeting line. Use placeholder |booker_name| where the booker's name should appear (e.g., 'Cześć |booker_name|,'). Leave empty for translated default.",
                    ),
                ),
                (
                    "intro_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered above the booking facts."),
                ),
                (
                    "label_datetime",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the date & time row.", max_length=256
                    ),
                ),
                (
                    "label_email",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the email row.", max_length=256
                    ),
                ),
                (
                    "label_phone",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the phone row.", max_length=256
                    ),
                ),
                (
                    "label_company",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the company row.", max_length=256
                    ),
                ),
                (
                    "label_message",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the message row.", max_length=256
                    ),
                ),
                (
                    "label_video",
                    models.CharField(
                        blank=True, default="", help_text="Inline label before the video meeting link.", max_length=256
                    ),
                ),
                (
                    "closing_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered after the meet link."),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Contact Forms] Booking Confirmation",
                "verbose_name_plural": "[Contact Forms] Booking Confirmations",
            },
        ),
        migrations.CreateModel(
            name="ContactFormsClientCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                (
                    "intro_copy",
                    models.TextField(
                        blank=True, default="", help_text="Paragraph rendered above the submission facts."
                    ),
                ),
                (
                    "label_email",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the email row.", max_length=256
                    ),
                ),
                (
                    "label_type",
                    models.CharField(blank=True, default="", help_text="Table label for the type row.", max_length=256),
                ),
                (
                    "label_form",
                    models.CharField(blank=True, default="", help_text="Table label for the form row.", max_length=256),
                ),
                (
                    "label_code",
                    models.CharField(blank=True, default="", help_text="Table label for the code row.", max_length=256),
                ),
                (
                    "label_body",
                    models.CharField(blank=True, default="", help_text="Table label for the body row.", max_length=256),
                ),
                (
                    "closing_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered after the body."),
                ),
                (
                    "header_title",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="H2 heading at the top of the email. Overrides 'Thank you for contacting us' default.",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Contact Forms] Client Copy",
                "verbose_name_plural": "[Contact Forms] Client Copies",
            },
        ),
        migrations.CreateModel(
            name="ContactFormsSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                (
                    "intro_copy",
                    models.TextField(
                        blank=True, default="", help_text="Paragraph rendered above the submission facts."
                    ),
                ),
                (
                    "label_email",
                    models.CharField(
                        blank=True, default="", help_text="Table label for the email row.", max_length=256
                    ),
                ),
                (
                    "label_type",
                    models.CharField(blank=True, default="", help_text="Table label for the type row.", max_length=256),
                ),
                (
                    "label_form",
                    models.CharField(blank=True, default="", help_text="Table label for the form row.", max_length=256),
                ),
                (
                    "label_code",
                    models.CharField(blank=True, default="", help_text="Table label for the code row.", max_length=256),
                ),
                (
                    "label_body",
                    models.CharField(blank=True, default="", help_text="Table label for the body row.", max_length=256),
                ),
                (
                    "closing_copy",
                    models.TextField(blank=True, default="", help_text="Paragraph rendered after the body."),
                ),
                (
                    "header_title",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="H2 heading at the top of the email. Overrides 'New contact form submission' default.",
                    ),
                ),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Contact Forms] Submission",
                "verbose_name_plural": "[Contact Forms] Submissions",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCouponConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                ("thank_you", models.TextField(blank=True, null=True)),
                ("coupon_copy", models.TextField(blank=True, null=True)),
                ("coupon_button", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Loyalty] Coupon Confirmation",
                "verbose_name_plural": "[Loyalty] Coupon Confirmations",
            },
        ),
        migrations.CreateModel(
            name="ReturnsReturnConfirmation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "welcome",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add user name, please fill this field with |user_name|",
                        null=True,
                    ),
                ),
                (
                    "return_copy",
                    models.TextField(
                        blank=True,
                        help_text="If you want to add order ID or return ID, please fill this field with |order_id| |return_id|",
                        null=True,
                    ),
                ),
                ("comment_copy", models.TextField(blank=True, null=True)),
                ("print_copy", models.TextField(blank=True, null=True)),
                ("help", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_email.channel")),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only languages that are enabled in django_email setting EMAIL_AVAILABLE_LANGUAGES works.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Returns] Return Confirmation",
                "verbose_name_plural": "[Returns] Return Confirmations",
            },
        ),
        migrations.CreateModel(
            name="LangChannelConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="ISO2 language code (e.g., 'pl', 'en'). Leave empty for default/fallback configuration. Priority: specific language (e.g., 'pl') takes precedence over default (None).",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("shop_name", models.CharField(blank=True, max_length=256, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("header_mail", models.EmailField(max_length=254)),
                (
                    "footer_copy",
                    models.TextField(blank=True, help_text="Footer copy text for this language", null=True),
                ),
                ("footer_name_brand", models.CharField(blank=True, max_length=256, null=True)),
                ("footer_link_brand", models.URLField(blank=True, null=True)),
                ("footer_link_facebook", models.URLField(blank=True, null=True)),
                ("footer_link_instagram", models.URLField(blank=True, null=True)),
                ("footer_link_youtube", models.URLField(blank=True, null=True)),
                ("footer_link_x", models.URLField(blank=True, null=True)),
                ("footer_link_tiktok", models.URLField(blank=True, null=True)),
                (
                    "footer_signature_copy_1",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="First line of footer signature (e.g., 'Pozdrawiamy,'). Leave empty to use translated default.",
                    ),
                ),
                (
                    "footer_signature_copy_2",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Second line of footer signature (e.g., 'Ekipa'). Rendered next to brand link.",
                    ),
                ),
                (
                    "footer_socials_copy",
                    models.TextField(
                        blank=True, default="", help_text="Copy displayed before social links (e.g., 'Obserwuj nas:')."
                    ),
                ),
                (
                    "footer_automatic_copy",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Disclaimer at the bottom of every email (e.g., 'To jest wiadomość automatyczna...').",
                    ),
                ),
                (
                    "footer_unsubscribe_label",
                    models.TextField(
                        blank=True, default="", help_text="Label for the unsubscribe link (e.g., 'Wypisz się')."
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Channel to which this configuration belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lang_configs",
                        to="django_email.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["channel", "language"],
                "unique_together": {("channel", "language")},
            },
        ),
    ]
